name: eight

description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^0.21.0
  graphql_flutter: ^2.0.0
  flutter_html: ^0.11.0
  transparent_image: ^1.0.0
  cached_network_image: ^1.1.1
  shared_preferences: ^0.5.3+4
  multi_image_picker: ^4.5.6
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
  assets:
    - assets/config/countries.json
    - assets/images/user_bg.jpg
  fonts:
    - family: EvaIcons
      fonts:
        - asset: assets/fonts/EvaIcons.ttf
    - family: TaobaoIcons
      fonts:
        - asset: assets/fonts/TaobaoIcons.ttf

